## set only when compiled in release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[release]
port = 9999
secret_key = "3cpmX05o3JJ/oWBe3EKIseLoskJTkBHyfidz6JluwJg="